name: Build and Publish RSS

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"   # hourly

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser feedgen

      - name: Build main feed
        run: |
          mkdir -p public
          echo "ok" > public/index.html
          python emea_feed_relay.py --output public/emea-filtered.xml --max-items 200

      - name: "Build 24h Watchlist Top 5 (table: Country · Headline · Source)"
        run: |
          python - << 'PY'
          import re, html, time, feedparser, os
          from urllib.parse import urlparse

          FEED_PATH = "public/emea-filtered.xml"
          owner, repo = os.environ["GITHUB_REPOSITORY"].split("/")
          BASE = f"https://{owner}.github.io/{repo}/"

          d = feedparser.parse(FEED_PATH)
          cutoff = time.time() - 24*3600

          # --- GEO GUARD (strict) ---
          EMEA_TERMS = re.compile(
            r"(Europe|EU|European Union|Schengen|Eurozone|Middle East|Gulf|Levant|Maghreb|North Africa|"
            r"UK|United Kingdom|England|Scotland|Wales|Northern Ireland|Ireland|France|Germany|Austria|Switzerland|Netherlands|Belgium|Denmark|Norway|Sweden|Finland|Iceland|Poland|Czech|Slovakia|Hungary|Romania|Bulgaria|Greece|Italy|Spain|Portugal|Ukraine|Estonia|Latvia|Lithuania|Serbia|Bosnia|Croatia|Slovenia|Albania|Kosovo|Moldova|"
            r"Israel|Palestine|Gaza|West Bank|Lebanon|Syria|Jordan|Egypt|Turkey|Türkiye|Cyprus|Qatar|Saudi Arabia|United Arab Emirates|UAE|Bahrain|Kuwait|Oman|Yemen|Iraq|Iran|Libya|Tunisia|Algeria|Morocco)",
            re.I
          )
          WATCHLIST = re.compile(
            r"(london|plymouth|sheffield|abingdon|kyiv|kiev|doha|riyadh|dubai|zurich|yverdon-les-bains|"
            r"stockholm|oslo|copenhagen|vienna|eindhoven|amsterdam|tel\s*-?\s*aviv|jerusalem|hamburg|berlin|paris|"
            r"heathrow|lhr|gatwick|lgw|stansted|stn|luton|ltn|london city|lcy|cdg|charles de gaulle|orly|ory|"
            r"gare du nord|schiphol|ams|zrh|vie|cph|arn|osl|tlv)",
            re.I,
          )
          NON_EMEA_STRONG = re.compile(
            r"(American|United States|U\.?S\.?A\.?|U\.?S\.?|Canada|Canadian|Mexico|Mexican|Brazil|Brazilian|Argentina|Argentinian|Chile|Peru|"
            r"Republican|Democrat|GOP|Congress|Senate|House of Representatives|Supreme Court|SCOTUS|District Attorney|county sheriff|"
            r"Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming|"
            r"New York|Los Angeles|Chicago|Houston|Phoenix|Philadelphia|San Antonio|San Diego|Dallas|San Jose|Miami|Atlanta|Washington,?\s*D\.?C\.?)",
            re.I
          )
          EMEA_TLDS = (".uk",".ie",".fr",".de",".nl",".be",".lu",".dk",".no",".se",".fi",".is",".ch",".at",".it",".es",".pt",".pl",".cz",".sk",".hu",".ro",".bg",".gr",".si",".hr",".ba",".rs",".me",".al",".mk",".lt",".lv",".ee",".ua",".md",".tr",".cy",".il",".ps",".lb",".sy",".jo",".eg",".ma",".dz",".tn",".ly",".sa",".qa",".ae",".kw",".bh",".om",".ye")
          EMEA_DOMAINS = ("bbc.co.uk","bbc.com","france24.com","euronews.com","dw.com","timesofisrael.com","jpost.com","middleeastmonitor.com","aa.com.tr","aljazeera.com","sky.com","skynews.com","reuters.com","afp.com","apnews.com","cnn.com","trtworld.com")

          # --- SIGNAL PATTERNS (protests strongly boosted) ---
          VIOLENCE = re.compile(r"\b(stabbing|knife attack|shooting|gunfire|shots fired|explosion|blast|bomb|grenade|arson|riots?|clashes|unrest|hostage|kidnap|terror)\b", re.I)
          CASUALTY = re.compile(r"\b(killed|dead|deaths|fatal|injured|wounded|casualties)\b", re.I)
          TRANS_HARD = re.compile(r"(airport|airspace|runway|rail|train|metro|tram|port|harbour|harbor|ferry).*?(closed|suspended|halted|blocked|shutdown)|all\s+lanes\s+closed|carriageway\s+closed|road\s+closed|blocked|drone.*(airport|airspace)", re.I)
          PROTEST   = re.compile(r"\b(protest|demonstration|march|strike|walkout|blockade)\b", re.I)
          SCALE     = re.compile(r"mass (?:protest|demonstration)s?|nationwide|countrywide|tens? of thousands|hundreds? of (?:people|protesters)|general|national strike|roadblocks?|highways? blocked|airport (?:blocked|closed)", re.I)
          ENFORCE   = re.compile(r"riot police|tear gas|water cannon|clashes with police|arrests?|detained", re.I)
          GOV       = re.compile(r"curfew|state of emergency|martial law|emergency decree|security alert raised", re.I)
          EVAC      = re.compile(r"evacuated|evacuation|terminal evacuated|station evacuated|building evacuated", re.I)

          def ts(e):
              for k in ("published_parsed","updated_parsed"):
                  v = getattr(e, k, None)
                  if v: return time.mktime(v)
              return time.time()

          def is_emea(text, link):
              t = text or ""
              if NON_EMEA_STRONG.search(t) and not (EMEA_TERMS.search(t) or WATCHLIST.search(t)):
                  return False
              if WATCHLIST.search(t) or EMEA_TERMS.search(t):
                  return True
              try:
                  host = urlparse(link).netloc.lower()
                  if any(host.endswith(tld) for tld in EMEA_TLDS): return True
                  if any(dom in host for dom in EMEA_DOMAINS): return True
              except Exception:
                  pass
              return False

          def qualifies(e):
              t_ = ts(e)
              if t_ < cutoff: return False
              title = getattr(e,'title',''); summary = getattr(e,'summary',''); link = getattr(e,'link','')
              text = f"{title} {summary}"
              if not is_emea(text, link): return False
              return bool(VIOLENCE.search(text) or CASUALTY.search(text) or TRANS_HARD.search(text) or PROTEST.search(text))

          def score(e):
              text = f"{getattr(e,'title','')} {getattr(e,'summary','')}"
              s = 0
              if VIOLENCE.search(text): s += 90
              if CASUALTY.search(text): s += 35
              if TRANS_HARD.search(text): s += 70
              if PROTEST.search(text): s += 55
              if SCALE.search(text): s += 35
              if ENFORCE.search(text): s += 30
              if GOV.search(text): s += 40
              if EVAC.search(text): s += 50
              age_h = (time.time() - ts(e))/3600
              s += 10 if age_h <= 6 else (5 if age_h <= 24 else 0)
              return s

          COUNTRY_PATTERNS = [
            ("United Kingdom", re.compile(r"\b(uk|united kingdom|britain|english|scottish|welsh|london|heathrow|lhr|gatwick|lgw|stansted|stn|luton|ltn|london city|lcy|paddington|king'?s cross|st\s*pancras|waterloo|victoria|liverpool street|london bridge|euston)\b", re.I)),
            ("France",         re.compile(r"\b(france|paris|cdg|charles de gaulle|orly|ory|gare du nord|gare de l'[eé]st|gare de lyon|montparnasse|saint[- ]lazare|austerlitz)\b", re.I)),
            ("Germany",        re.compile(r"\b(germany|berlin|hamburg|ber airport|berlin hbf|hamburg hbf)\b", re.I)),
            ("Netherlands",    re.compile(r"\b(netherlands|amsterdam|eindhoven|schiphol|ams|amsterdam centraal|eindhoven centraal|ein)\b", re.I)),
            ("Switzerland",    re.compile(r"\b(switzerland|zurich|zürich|zrh|zurich hb|zürich hb|yverdon-les-bains)\b", re.I)),
            ("Austria",        re.compile(r"\b(austria|vienna|wien hbf|vienna hbf|vie)\b", re.I)),
            ("Denmark",        re.compile(r"\b(denmark|copenhagen|københavn|kobenhavn|cph|kobenhavn h|københavn h)\b", re.I)),
            ("Norway",         re.compile(r"\b(norway|oslo|oslo s|gardermoen|osl)\b", re.I)),
            ("Sweden",         re.compile(r"\b(sweden|stockholm|arlanda|arn|stockholm central)\b", re.I)),
            ("Ukraine",        re.compile(r"\b(ukraine|kyiv|kiev|boryspil|kbp|zhuliany|iev|kyiv[- ]pasazhyrskyi)\b", re.I)),
            ("Qatar",          re.compile(r"\b(qatar|doha|hamad international|doh|msheireb)\b", re.I)),
            ("Saudi Arabia",   re.compile(r"\b(saudi arabia|riyadh|king khalid international|ruh|riyadh metro)\b", re.I)),
            ("United Arab Emirates", re.compile(r"\b(united arab emirates|uae|dubai|dxb|al maktoum|dwc|burjuman)\b", re.I)),
            ("Israel/Palestinian Territories", re.compile(r"\b(israel|palestine|gaza|west bank|tel[- ]?aviv|jerusalem|ben gurion|tlv)\b", re.I)),
            ("Morocco",        re.compile(r"\b(morocco|rabat|casablanca|marrakech|tangier|fes|agadir)\b", re.I)),
          ]

          def infer_country(text, link):
              t = text or ""
              for name, rx in COUNTRY_PATTERNS:
                  if rx.search(t): return name
              try:
                  host = urlparse(link).netloc.lower()
                  if host.endswith(".il"): return "Israel/Palestinian Territories"
                  if host.endswith(".uk"): return "United Kingdom"
                  if host.ends
