name: Build and Publish RSS

on:
  workflow_dispatch: {}         # allows manual runs
  schedule:
    - cron: "0 * * * *"         # runs hourly

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install feedparser feedgen

      - name: Build feed XML
        run: python emea_feed_relay.py --output docs/emea-filtered.xml --tiers tier1,tier2 --max-items 200

      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/emea-filtered.xml
          git commit -m "Update feed" || echo "No changes to commit"
          git push
