name: Build and Publish RSS
on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch: {}       # allow manual run from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install feedparser feedgen
      - run: python emea_feed_relay.py --output docs/emea-filtered.xml --tiers tier1,tier2 --max-items 200
      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: emea-filtered
          path: docs/emea-filtered.xml
