name: Build and Publish RSS

on:
  schedule:
    - cron: "*/10 * * * *"    # every 10 minutes
  workflow_dispatch: {}        # you can still run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install feedparser feedgen

      - run: python emea_feed_relay.py --output docs/emea-filtered.xml --tiers tier1,tier2 --max-items 200

      # ↓ Tiny addition vs earlier: commit the updated XML so GitHub Pages sees it
      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/emea-filtered.xml
          git commit -m "Update feed" || echo "No changes to commit"
          git push

      # Optional: artifact for quick download/debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: emea-filtered
          path: docs/emea-filtered.xml
